### PR TITLE
Add getUpperBounds getLowerBounds in JavaWildcardType

### PR DESCRIPTION
**Pull request by KnifeC**
Hello, I need to parse some code like 
`
List<? extends String> test = new ArrayList<>();
`
the field bounds of DefaultJavaWildcardType is important for me to process the type information.

I'm currently using reflect to get the information
```
Field bounds = DefaultJavaWildcardType.class.getDeclaredField( "bounds" );
bounds.setAccessible( true );
bounds.get( wildcardType );
```
It's really complex, so I added the get method to it.

### CODE REVIEW

**Comment by rfscholte** [comment]
I would prefer to stay closer to Javas [WildcardType](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/reflect/WildcardType.html)

**Comment by KnifeC** [comment]
So would it be better if I created the getLowerBounds() getUpperBounds() method in JavaWildcardType And also keep the get methods in DefaultJavaWildcardType?

**Comment by rfscholte** [comment]
I only want to see the getLowerBounds() and getUpperBounds(). If that means a change to DefaultJavaWildcardType, then that should be implemented too.

**Comment by KnifeC** [comment]
I have added getUpperBounds getLowerBounds in JavaWildcardType, and implemented them.

**Pull request merged**
